version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace    
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    command: sleep infinity
    network_mode: service:postgres

volumes:
  pgdata:
